name: Deploy to Vercel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel "BCR-ABL analyzer" --prod --yes --name bcr-abl-pcr-analysis --token ${{ secrets.VERCEL_TOKEN }}
